[package]
name = "cobalt-lang"
version = "0.9.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
colored = "3.0.0"
dialoguer = "0.11.0"
phf = { version = "0.11.3" , features = ["macros"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"

[profile.release]
lto = true