name: Build macOS Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build for macOS (x86_64 + aarch64)
    runs-on: macos-latest

    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the tag
        run: |
          git fetch --tags --force
          TAG=$(git describe --tags --abbrev=0 --always)
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build all binaries
        run: cargo build --release --target ${{ matrix.target }}

      - name: Set architecture name
        run: |
          if [[ "${{ matrix.target }}" == "x86_64-apple-darwin" ]]; then
            echo "ARCH_NAME=x86_64" >> $GITHUB_ENV
          else
            echo "ARCH_NAME=aarch64" >> $GITHUB_ENV
          fi

      - name: Upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: cobalt-${{ env.TAG_NAME }}-darwin-${{ env.ARCH_NAME }}
          path: |
            target/${{ matrix.target }}/release/cbproj
            target/${{ matrix.target }}/release/cobalt
            target/${{ matrix.target }}/release/cobalt-lang
