name: Build macOS Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for macOS (x86_64 + aarch64)
    runs-on: macos-latest

    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build all binaries
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/cbproj
            target/${{ matrix.target }}/release/cobalt
            target/${{ matrix.target }}/release/cobalt-lang
